version: '3'

networks:
  micro_red:
    driver: bridge
    name: micro_red


services:
  config-server:
    build: 
      context: ./ms-config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:7070
    networks:
      - micro_red
    container_name: config-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g

  registry-server:
    build: ms-registry-server
    ports:
      - 8090:8090

    restart: always
    networks:
      - micro_red
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    container_name: registry-server


  gateway-server:
    build: ms-gateway-server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - config-server
    networks:
      - micro_red
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    container_name: gateway-server
  
  admin-server:
    build: ms-admin-server
    restart: always
    ports:
      - 6060:6060
    depends_on:
      - config-server
    networks:
      - micro_red
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    container_name: admin-server
