version: '3'

networks:
  micro_red:
    driver: bridge
    name: micro_red


services:
  config-server:
    build: 
      context: ./ms-config-server
      dockerfile: Dockerfile
    ports:
      - 7070:7070
    networks:
      - micro_red
  
  registry-server:
    build: ms-registry-server
    ports:
      - 8090:8090
    depends_on:
      - config-server
    networks:
      - micro_red

  gateway-server:
    build: ms-gateway-server
    ports:
      - 8080:8080
    depends_on:
      - config-server
    networks:
      - micro_red
  
  admin-server:
    build: ms-admin-server
    ports:
      - 8080:8080
    depends_on:
      - config-server
    networks:
      - micro_red