version: '3'

networks:
  mi_red:
    driver: bridge

services:
  config-server:
    build: ms-config-server
    ports:
      - 7070:7070
    networks:
      - mi_red
  
  registry-server:
    build: ms-registry-server
    ports:
      - 8090:8090
    depends_on:
      - config-server
    networks:
      - mi_red

  gateway-server:
    build: ms-gateway-server
    ports:
      - 8080:8080
    depends_on:
      - config-server
    networks:
      - mi_red