

version: '3'

networks:
  micro_red:
    external: true
    name: micro_red

services:
  mysql-asistencia:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - micro_red
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ms_asistencia
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    container_name: mysql-asistencia
  
  ms-asistencia:
    build: .
    networks:
      - micro_red
    depends_on:
      - mysql-asistencia

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 1g

