version: '3'

networks:
  micro_red:
    external: true
    name: micro_red

services:
  
  ms-bff-asistencia-web:
    build: .
    networks:
      - micro_red
    
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 1g

