server:
  port: ${PORT:${SERVER_PORT:0}}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_configuracion
    username: root
    password:

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.aplication.name}:${spring.aplication.instance_id:${random.value}}



