server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry-server:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-bff-asistencia-web-service
          uri: lb://ms-bff-asistencia-web-service
          predicates:
            - Path=/institucion/**,/filial/**,/facultad/**,/escuela-profesional/**,/periodo/**,/persona/**,/ciclo**,/grupo**,/persona/matricula**,/evento/**,/asistencia/reporte**,/asistencia/registro**
          filters:
            - AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
        #- id: ms-evento-service
        #  uri: lb://ms-evento-service
        #  predicates:
        #    - Path=/evento/**
        #- id: ms-asistencia-service
        #  uri: lb://ms-asistencia-service
        #  predicates:
        #    - Path=/asistencia/**


