server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-configuracion-service
          uri: lb://ms-configuracion-service
          predicates:
            - Path=/institucion/**,/filial/**,/facultad/**,/escuela-profesional/**,/periodo/**,/persona/**,/ciclo/**,/grupo/**
        - id: ms-evento-service
          uri: lb://ms-evento-service
          predicates:
            - Path=/evento/**
        - id: ms-asistencia-service
          uri: lb://ms-asistencia-service
          predicates:
            - Path=/asistencia/**


