version: '3'

networks:
  micro_red:
    external: true
    name: micro_red

services:
  mysql-configuration:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - micro_red
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ms_configuracion
    ports:
      - 3308:3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    volumes:
      - db_data:/var/lib/mysql
  
  ms-configuration:
    build: .
    restart: always
    networks:
      - micro_red
    depends_on:
      - mysql-configuration
    
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
    

volumes:
  db_data: